.TH HELLOWORLD "1" "January 2016" "helloworld 0.1" ""
.SH NAME
helloworld \- just a "Hello, World!" program, nothing serious
.SH SYNOPSIS
.B helloworld
.SH DESCRIPTION
.PP
A "Hello, World!" program is a computer program that outputs "Hello, World!" on
a display device. Being a very simple program in most programming languages, it
is often used to illustrate to beginning programmers the basic syntax for
constructing a working program. It is also used to verify that a language or
system is operating correctly.
.SH "REPORTING BUGS"
There are no bugs. Don't try to report any.
